pokemon_list = [
  {
    "Name": "Bulbasaur",
    "Type 1": "Grass",
    "Type 2": "Poison",
    "Total": 318,
    "HP": 45,
    "Attack": 49,
    "Defense": 49,
    "Sp. Atk": 65,
    "Sp. Def": 65,
    "Speed": 45,
    "Generation": 1,
    "Legendary": "False"
  },
  {
    "Name": "Ivysaur",
    "Type 1": "Grass",
    "Type 2": "Poison",
    "Total": 405,
    "HP": 60,
    "Attack": 62,
    "Defense": 63,
    "Sp. Atk": 80,
    "Sp. Def": 80,
    "Speed": 60,
    "Generation": 1,
    "Legendary": "False"
  },
  {
    "Name": "Venusaur",
    "Type 1": "Grass",
    "Type 2": "Poison",
    "Total": 525,
    "HP": 80,
    "Attack": 82,
    "Defense": 83,
    "Sp. Atk": 100,
    "Sp. Def": 100,
    "Speed": 80,
    "Generation": 1,
    "Legendary": "False"
  },
  {
    "Name": "Charmander",
    "Type 1": "Fire",
    "Type 2": "",
    "Total": 309,
    "HP": 39,
    "Attack": 52,
    "Defense": 43,
    "Sp. Atk": 60,
    "Sp. Def": 50,
    "Speed": 65,
    "Generation": 1,
    "Legendary": "False"
  },
  {
    "Name": "Charmeleon",
    "Type 1": "Fire",
    "Type 2": "",
    "Total": 405,
    "HP": 58,
    "Attack": 64,
    "Defense": 58,
    "Sp. Atk": 80,
    "Sp. Def": 65,
    "Speed": 80,
    "Generation": 1,
    "Legendary": "False"
  },
  {
    "Name": "Charizard",
    "Type 1": "Fire",
    "Type 2": "Flying",
    "Total": 534,
    "HP": 78,
    "Attack": 84,
    "Defense": 78,
    "Sp. Atk": 109,
    "Sp. Def": 85,
    "Speed": 100,
    "Generation": 1,
    "Legendary": "False"
  }
]
